Add maintenance mode actions (#135)
* Add maintenance mode actions

Signed-off-by: Chi Wai Chan <chiwai.chan@canonical.com>

* Use positional arguments instead.

* Fix corner case.

Signed-off-by: Chi Wai Chan <chiwai.chan@canonical.com>

* Add basic functional test for maintenance mode.

Signed-off-by: Chi Wai Chan <chiwai.chan@canonical.com>

* Update maintenance actions to use microceph client

Signed-off-by: Chi Wai Chan <chiwai.chan@canonical.com>

* Improve error message

Signed-off-by: Chi Wai Chan <chiwai.chan@canonical.com>

* Add check-only option for maintenance mode for sunbeam

* Update api handling method

* Add ignore-check flag

Signed-off-by: Chi Wai Chan <chiwai.chan@canonical.com>

* Address comments.

Signed-off-by: Chi Wai Chan <chiwai.chan@canonical.com>

* Bump action versions.

Signed-off-by: Chi Wai Chan <chiwai.chan@canonical.com>

* Add more debugging information during tests.

Signed-off-by: Chi Wai Chan <chiwai.chan@canonical.com>

* Remove --config default-pool-size=1 for maintenance tests.

Signed-off-by: Chi Wai Chan <chiwai.chan@canonical.com>

* Refactor maintenance mode code to maintenance.py

Signed-off-by: Chi Wai Chan <chiwai.chan@canonical.com>

* Fix typo in functional test

Signed-off-by: Chi Wai Chan <chiwai.chan@canonical.com>

* Temporarily use squid/edge to test maintenance mode

* Refactor: remove duplicated code

Signed-off-by: Chi Wai Chan <chiwai.chan@canonical.com>

---------

Signed-off-by: Chi Wai Chan <chiwai.chan@canonical.com>

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -215,6 +215,203 @@ jobs:
         if: ${{ failure() && runner.debug }}
         uses: canonical/action-tmate@main
 
+  juju-cluster-maintenance-test:
+    needs:
+      - lint
+      - unit-test
+      - build
+    name: Juju cluster maintenance test
+    runs-on: [self-hosted, xlarge]
+    steps:
+
+      - name: Download charm
+        uses: actions/download-artifact@v4
+        with:
+          name: charms
+          path: ~/artifacts/
+
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Setup LXD
+        uses: canonical/setup-lxd@v0.1.1
+        with:
+          # pin lxd to LTS release.
+          channel: 5.21/stable
+
+      - name: Install dependencies
+        run: ./tests/scripts/ci_helpers.sh install_deps
+
+      - name: Install MicroCeph charm
+        run: |
+          date
+          # FIXME: change to squid/stable when maintenance feature is landed
+          juju deploy -n 4 ~/artifacts/microceph.charm --config snap-channel=squid/edge
+          ./tests/scripts/ci_helpers.sh wait_for_microceph_bootstrap
+          date
+
+      - name: Show Juju status
+        run: |
+          set -eux
+          juju status
+
+      - name: Enable one extra ceph mon for redundancy
+        run: |
+          set -eux
+
+          echo "Make sure all units have ceph monitor enabled."
+
+          for i in 0 1 2 3 ; do
+            juju ssh microceph/$i -- sudo microceph enable mon || true
+          done
+
+      - name: Add disks
+        run: |
+          set -eux
+          juju run microceph/0 add-osd loop-spec=4G,1 --wait=2m
+          juju run microceph/1 add-osd loop-spec=4G,1 --wait=2m
+          juju run microceph/2 add-osd loop-spec=4G,1 --wait=2m
+          juju run microceph/3 add-osd loop-spec=4G,1 --wait=2m
+
+      - name: Show Ceph status
+        run: |
+          set -eux
+          juju ssh microceph/0 -- sudo microceph status
+          juju ssh microceph/0 -- sudo microceph.ceph -s
+
+      - name: Assert Ceph is in healthy state before running test
+        run: |
+          set -eux
+          juju ssh microceph/0 -- sudo microceph.ceph health | grep HEALTH_OK
+
+      - name: Dry run test
+        run: |
+          set -eux
+
+          echo "Test dry running enter-maintenance and exit-maintenance actions."
+
+          result=$(juju run microceph/0 exit-maintenance dry-run=true --format json)
+          echo $result
+
+          action_counts=$(echo $result | jq '."microceph/0".results.actions | length')
+          if [ "$action_counts" != "3" ] ; then
+            echo "Expect dry run exit-maintenance to produce 3 steps."
+            exit 1
+          fi
+
+          result=$(juju run microceph/0 enter-maintenance dry-run=true --format json)
+          echo $result
+
+          action_counts=$(echo $result | jq '."microceph/0".results.actions | length')
+          if [ "$action_counts" != "4" ] ; then
+            echo "Expect dry run enter-maintenance to produce 3 steps."
+            exit 1
+          fi
+
+      - name: Test enter maintenance mode okay
+        run: |
+          set -eux
+
+          echo "Test running enter-maintenance action."
+
+          result=$(juju run microceph/3 enter-maintenance stop-osds=true --format json)
+          echo $result
+
+          status=$(echo $result | jq '."microceph/3".results.status' -r )
+          if [ "$status" != "success" ] ; then
+            echo "Expect enter-maintenance to succeed."
+            exit 1
+          fi
+
+          if ! $(juju ssh microceph/3 -- sudo microceph.ceph osd dump | grep noout > /dev/null 2>&1) ; then
+            echo "Expect osd noout is set"
+            exit 1
+          fi
+
+          if ! $(juju ssh microceph/3 -- snap services microceph.osd | grep inactive > /dev/null 2>&1) ; then
+            echo "Expect osd service is inactive"
+            exit 1
+          fi
+
+          if ! $(juju ssh microceph/3 -- snap services microceph.osd | grep disabled > /dev/null 2>&1) ; then
+            echo "Expect osd service is disabled"
+            exit 1
+          fi
+
+      - name: Test exit maintenance mode okay
+        run: |
+          set -eux
+
+          echo "Test running exit-maintenance action."
+
+          result=$(juju run microceph/3 exit-maintenance --format json)
+          echo $result
+
+          status=$(echo $result | jq '."microceph/3".results.status' -r )
+          if [ "$status" != "success" ] ; then
+            echo "Expect exit-maintenance to succeed."
+            exit 1
+          fi
+
+          if $(juju ssh microceph/3 -- sudo microceph.ceph osd dump | grep noout > /dev/null 2>&1) ; then
+            echo "Expect osd noout is unset"
+            exit 1
+          fi
+
+          if ! $(juju ssh microceph/3 -- snap services microceph.osd | grep active > /dev/null 2>&1) ; then
+            echo "Expect osd service is active"
+            exit 1
+          fi
+
+          if ! $(juju ssh microceph/3 -- snap services microceph.osd | grep enabled > /dev/null 2>&1) ; then
+            echo "Expect osd service is enabled"
+            exit 1
+          fi
+
+      - name: Remove Unit
+        run: |
+          set -x
+          ./tests/scripts/ci_helpers.sh remove_unit_wait "microceph/3"
+
+      - name: Test enter maintenance mode fail
+        run: |
+          set -eux
+
+          echo "Test running enter-maintenance action (fail case)."
+
+          result=$(juju run microceph/2 enter-maintenance stop-osds=true --format json)
+          echo $result
+
+          has_errors=$(echo $result | jq '."microceph/2".results.errors != ""')
+          if [ "$has_errors" != "true" ] ; then
+            echo "Expect enter-maintenance to fail with error message because there is only 3 nodes."
+            exit 1
+          fi
+
+          status_failure=$(echo $result | jq '."microceph/2".results.status == "failure"')
+          if [ "$status_failure" != "true" ] ; then
+            echo "Expect enter-maintenance to fail with status=failure."
+            exit 1
+          fi
+
+      - name: Collect logs
+        if: failure()
+        run: ./tests/scripts/ci_helpers.sh collect_microceph_logs
+
+      - name: Upload logs
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: microceph_juju_cluster_test_logs
+          path: logs
+          retention-days: 30
+
+      - name: Setup tmate session
+        if: ${{ failure() && runner.debug }}
+        uses: canonical/action-tmate@main
+
   juju-single-test:
     needs:
       - lint
@@ -581,7 +778,7 @@ jobs:
       - lint
       - unit-test
       - build
-    name: Juju multi node storage test 
+    name: Juju multi node storage test
     runs-on: [self-hosted, xlarge]
     steps:
       - name: Download charm
@@ -608,7 +805,7 @@ jobs:
         run: |
           date
           mv ~/artifacts/microceph.charm ./microceph.charm
-          juju deploy ./tests/bundles/multi_node_juju_storage.yaml 
+          juju deploy ./tests/bundles/multi_node_juju_storage.yaml
           # wait for charm to bootstrap and OSD devices to enroll.
           ./tests/scripts/ci_helpers.sh wait_for_microceph_bootstrap
           date
@@ -635,8 +832,8 @@ jobs:
           juju add-unit microceph -n 1
           sleep 60s
           juju wait-for unit microceph/3 --query='workload-message=="(workload) charm is ready"' --timeout=20m
-          
-           # "juju" substring is a part of all hosts, so it will fetch total OSD count 
+
+           # "juju" substring is a part of all hosts, so it will fetch total OSD count
           ./tests/scripts/ci_helpers.sh ensure_osd_count_on_host "juju" 9
 
       - name: Collect logs
