Added support for Juju Storage (#37)
* Added event handling for Juju Storage events.

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* added directive filter

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Experiments with guard section.

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Simplified detaching logic

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* modifs

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Final touch-ups

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Lint Fixes

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* More linting and functional test polishing.

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* import reordering

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* housekeeping

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Fixed Func Test

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Tweak Github Runner size.

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Added single unit tests

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* CI and Review fixes.

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Fixes for Juju CI tests

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Resolved review comments

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Added doc in readme

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Snap connect to mount-observe interface.

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* CI fixes

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Added artificial delay to test CI

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Modified Implementation to accomodate feedback

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Fixed lint and refactored CI osd count check.

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Removed dedicated DB storage directive.

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Re-Add the temp fix for "mount-observe"

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* ci patch

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Resolved review comments.

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Changed stored state cleaning to pop items.

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Housekeeping

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

* Condensed two lines into one.

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

---------

Signed-off-by: Utkarsh Bhatt <utkarsh.bhatt@canonical.com>

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -111,8 +111,8 @@ jobs:
           sudo microceph.ceph -s
           ~/actionutils.sh wait_for_osds 3
           sudo microceph.ceph -s
-          
-  juju-test:
+
+  juju-cluster-test:
     needs:
       - lint
       - unit-test
@@ -134,6 +134,9 @@ jobs:
 
       - name: Setup LXD
         uses: canonical/setup-lxd@v0.1.1
+        with:
+          # pin lxd since there were some recurring issues in recent releases.
+          channel: 5.18/stable
 
       - name: Install dependencies
         run: |
@@ -163,6 +166,91 @@ jobs:
           juju run microceph/1 add-osd loop-spec=4G,1 --wait=2m
           juju run microceph/2 add-osd loop-spec=4G,1 --wait=2m
 
+      - name: Remove Unit
+        run: |
+          set -x
+          juju remove-unit microceph/2 --no-prompt
+          # wait and check if the unit is still present.
+          for i in $(seq 1 20); do
+            res=$( ( juju status | grep -cF "microceph/2" ) || true )
+            if [[ $res -gt 0 ]] ; then
+              echo -n '.'
+              sleep 5
+            else
+              echo "Unit removed successfully"
+              break
+            fi
+          done
+          # fail if unit still present.
+          if [[ $res -gt 0 ]] ; then
+            echo "Unit still present"
+            juju status
+            exit 1
+          fi
+
+  juju-single-test:
+    needs:
+      - lint
+      - unit-test
+      - build
+    name: Juju test
+    runs-on: [self-hosted, xlarge]
+    steps:
+
+      - name: Download charm
+        uses: actions/download-artifact@v3
+        with:
+          name: charms
+          path: ~/artifacts/
+
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Setup LXD
+        uses: canonical/setup-lxd@v0.1.1
+        with:
+          # pin lxd since there were some recurring issues in recent releases.
+          channel: 5.18/stable
+
+      - name: Install dependencies
+        run: |
+          date
+          sudo apt-get -qq install jq
+          sudo snap install juju
+          mkdir -p ~/.local/share/juju
+          juju bootstrap localhost
+          juju add-model microceph-test
+          date
+
+      - name: Install MicroCeph charm
+        run: |
+          set -eux
+          date
+          # constraints to deploy on virtual machine.
+          juju deploy ~/artifacts/microceph.charm --storage osd-standalone='4G,3' --constraints="virt-type=virtual-machine root-disk=40G mem=8G"
+          # wait for charm to bootstrap and OSD devices to enroll.
+          juju wait-for unit microceph/0 --query='workload-message=="(workload) charm is ready"'
+          bash ./tests/scripts/ci_helpers.sh check_osd_count microceph/0 3
+          date
+
+      - name: Remove Juju Storage
+        run: |
+          set -eux
+          juju detach-storage osd-standalone/0
+          juju wait-for unit microceph/0 --query='workload-status=="blocked"'
+          bash tests/scripts/ci_helpers.sh check_osd_count microceph/0 2
+          date
+
+      - name: Add another OSD
+        run: |
+          set -eux
+          juju add-storage microceph/0 osd-standalone='4G,1'
+          juju wait-for unit microceph/0 --query='workload-message=="(workload) charm is ready"'
+          bash tests/scripts/ci_helpers.sh check_osd_count microceph/0 3
+          date
+
       - name: Add and relate RadosGW charm
         run: |
           set -eux
@@ -188,25 +276,4 @@ jobs:
             exit 1
           fi
 
-      - name: Remove Unit
-        run: |
-          set -x
-          juju remove-unit microceph/2 --no-prompt
-          # wait and check if the unit is still present.
-          for i in $(seq 1 8); do
-            res=$( ( juju status | grep -cF "microceph/2" ) || true )
-            if [[ $res -gt 0 ]] ; then
-              echo -n '.'
-              sleep 5
-            else
-              echo "Unit removed successfully"
-              break
-            fi
-          done
-          # fail if unit still present.
-          if [[ $res -gt 0 ]] ; then
-            echo "Unit still present"
-            juju status
-            exit 1
-          fi
-          juju exec --unit microceph/0 -- microceph status
+
